//! Registry of canonical examples for the envelope contract (adr/0015; the
//! carpenter adr/008 analog). Every `Data` variant has exactly one example
//! here, keyed by its command — the smoke test drives each through
//! [`crate::core::output::render`], pinning the exact envelope schema and the
//! `data` round-trip, so a payload shape change fails loudly. The strict
//! build gate cross-checks that every `Data` variant appears in this file
//! (phase 5), so a new variant cannot merge without an example.

use serde_json::json;

use crate::core::meta::HistoryEntry;
use crate::models::data::{
    AppliedFormat, CellText, CoreProperties, Data, DocumentInfo, FindResult, ImageInfo,
    ParagraphInfo, RunInfo, SectionDetail, SectionInfo, StyleInfo, TableInfo,
};

/// One canonical example per `Data` variant: `(command label, payload)`.
pub fn envelope_examples() -> Vec<(&'static str, Data)> {
    // `mut` is only consumed by the dev extend below.
    #[cfg_attr(not(feature = "dev"), allow(unused_mut))]
    let mut out: Vec<(&'static str, Data)> = vec![
        // ---- document ----
        (
            "document new",
            Data::DocumentNew {
                path: "report.docx".into(),
                message: "Document created".into(),
            },
        ),
        (
            "document open",
            Data::DocumentOpened {
                path: "report.docx".into(),
                message: "Document opened".into(),
            },
        ),
        (
            "document save",
            Data::DocumentSaved {
                path: "report.docx".into(),
                message: "Document saved".into(),
            },
        ),
        (
            "document close",
            Data::DocumentClosed {
                message: "Document closed".into(),
            },
        ),
        (
            "document info",
            Data::DocumentInfo(DocumentInfo {
                paragraph_count: 12,
                table_count: 2,
                section_count: 1,
                image_count: 1,
                bookmark_count: 15,
                core_properties: CoreProperties {
                    title: "Quarterly Report".into(),
                    author: "Poet".into(),
                    subject: "Q3 results".into(),
                    keywords: String::new(),
                    category: String::new(),
                    comments: "Generated by Poet".into(),
                    created: "2026-09-18T10:00:00".into(),
                    modified: "2026-09-18T10:05:00".into(),
                },
            }),
        ),
        (
            "document export",
            Data::DocumentExported {
                path: "report.md".into(),
                format: "md".into(),
                message: "Exported to report.md".into(),
            },
        ),
        // ---- paragraph ----
        (
            "paragraph add",
            Data::ParagraphAdded {
                id: "para1".into(),
                text: "Hello world.".into(),
                style: None,
                page_break: false,
                message: "Paragraph added".into(),
            },
        ),
        (
            "paragraph insert",
            Data::ParagraphInserted {
                id: "para2".into(),
                index: 1,
                text: "Inserted.".into(),
                style: None,
                page_break: false,
                message: "Paragraph inserted".into(),
            },
        ),
        (
            "paragraph get",
            Data::ParagraphGot {
                id: Some("para1".into()),
                index: None,
                text: "Hello world.".into(),
            },
        ),
        (
            "paragraph get (cell)",
            Data::ParagraphGotCell {
                table: 0,
                row: 0,
                col: 1,
                para: None,
                text: CellText::Many(vec!["Revenue".into(), "Growth".into()]),
            },
        ),
        (
            "paragraph update",
            Data::ParagraphUpdated {
                id: None,
                index: Some(0),
                text: "Updated text.".into(),
                message: "Paragraph updated".into(),
            },
        ),
        (
            "paragraph delete",
            Data::ParagraphDeleted {
                id: Some("para2".into()),
                index: None,
                message: "Paragraph deleted".into(),
            },
        ),
        (
            "paragraph delete (cell)",
            Data::CellParagraphDeleted {
                table: 0,
                row: 0,
                col: 0,
                para: 0,
                message: "Cell paragraph deleted".into(),
            },
        ),
        (
            "paragraph list",
            Data::ParagraphList {
                paragraphs: vec![ParagraphInfo {
                    index: 0,
                    id: Some("para1".into()),
                    style: Some("Normal".into()),
                    text: "Hello world.".into(),
                }],
            },
        ),
        (
            "paragraph move",
            Data::ParagraphMoved {
                id: None,
                index: 2,
                direction: "down".into(),
                message: "Paragraph moved down to index 2".into(),
            },
        ),
        (
            "paragraph clear",
            Data::ParagraphCleared {
                id: Some("para1".into()),
                index: None,
                message: "Paragraph cleared".into(),
            },
        ),
        (
            "paragraph border",
            Data::ParagraphBorder {
                id: None,
                index: Some(0),
                position: "bottom".into(),
                color: "FF0000".into(),
                size: 12,
                space: 1,
                style: "single".into(),
                message: "Bottom border applied".into(),
            },
        ),
        (
            "paragraph find",
            Data::ParagraphFound {
                text: "Revenue".into(),
                results: vec![
                    FindResult::Paragraph {
                        kind: "paragraph".into(),
                        index: 3,
                        text: "Revenue grew 12%.".into(),
                    },
                    FindResult::TableCell {
                        kind: "table_cell".into(),
                        table_index: 0,
                        row: 0,
                        col: 1,
                        text: "Revenue".into(),
                    },
                ],
                count: 2,
                message: "Found 2 matches".into(),
            },
        ),
        (
            "paragraph replace",
            Data::ParagraphReplaced {
                find: "Q2".into(),
                replace: "Q3".into(),
                count: 4,
                message: "Replaced 4 occurrences".into(),
            },
        ),
        ("paragraph count", Data::ParagraphCount { count: 12 }),
        // ---- run ----
        (
            "run add",
            Data::RunAdded {
                id: Some("para1".into()),
                index: None,
                text: "emphasis".into(),
                bold: Some(true),
                italic: None,
                underline: None,
                font: None,
                size: None,
                color: None,
                message: "Run added".into(),
            },
        ),
        (
            "run get",
            Data::RunsGot {
                id: None,
                index: Some(0),
                runs: vec![RunInfo {
                    text: "Hello ".into(),
                    bold: None,
                    italic: None,
                    underline: None,
                    font: Some("Calibri".into()),
                    size: Some(11.0),
                    color: None,
                }],
            },
        ),
        (
            "run get (cell)",
            Data::RunsGotCell {
                table: 0,
                row: 0,
                col: 0,
                para: None,
                runs: vec![RunInfo {
                    text: "Region".into(),
                    bold: Some(true),
                    italic: None,
                    underline: None,
                    font: None,
                    size: None,
                    color: None,
                }],
            },
        ),
        (
            "run clear",
            Data::RunsCleared {
                id: Some("para1".into()),
                index: None,
                message: "Runs cleared".into(),
            },
        ),
        (
            "run format",
            Data::RunFormatted {
                id: None,
                index: Some(0),
                run_index: None,
                applied: AppliedFormat {
                    bold: Some(true),
                    italic: None,
                    underline: None,
                    font_name: None,
                    font_size: Some(14.0),
                    color: Some("1F4E79".into()),
                },
                message: "Formatted 1 run(s)".into(),
            },
        ),
        (
            "run emphasize",
            Data::RunEmphasized {
                id: None,
                index: Some(0),
                table: None,
                row: None,
                col: None,
                para: None,
                find: "urgent".into(),
                replacements: 1,
                message: "Emphasized 1 occurrence(s)".into(),
            },
        ),
        // ---- style ----
        (
            "style list",
            Data::StylesListed {
                styles: vec![StyleInfo {
                    name: "Heading 1".into(),
                    r#type: "PARAGRAPH (1)".into(),
                    builtin: true,
                }],
                count: 1,
            },
        ),
        (
            "style apply",
            Data::StyleApplied {
                id: None,
                index: Some(0),
                style: "Intense Quote".into(),
                message: "Style applied".into(),
            },
        ),
        // ---- heading ----
        (
            "heading add",
            Data::HeadingAdded {
                id: "head1".into(),
                text: "Overview".into(),
                level: 1,
                message: "Heading added".into(),
            },
        ),
        (
            "heading set-level",
            Data::HeadingLevelSet {
                id: Some("head1".into()),
                index: None,
                level: 2,
                message: "Heading level set".into(),
            },
        ),
        (
            "heading list",
            Data::HeadingList {
                headings: vec![ParagraphInfo {
                    index: 0,
                    id: Some("head1".into()),
                    style: Some("Heading 1".into()),
                    text: "Overview".into(),
                }],
            },
        ),
        // ---- list ----
        (
            "list add",
            Data::ListItemAdded {
                id: "list1".into(),
                text: "First item".into(),
                list_type: "bullet".into(),
                level: 1,
                message: "List item added".into(),
            },
        ),
        (
            "list add-item",
            Data::ListItemAdded {
                id: "list1".into(),
                text: "Second item".into(),
                list_type: "bullet".into(),
                level: 1,
                message: "List item added".into(),
            },
        ),
        (
            "list convert",
            Data::ListConverted {
                id: Some("list1".into()),
                index: None,
                list_type: "ordered".into(),
                message: "List converted".into(),
            },
        ),
        (
            "list set-level",
            Data::ListLevelSet {
                id: Some("list1".into()),
                index: None,
                level: 2,
                message: "List level set".into(),
            },
        ),
        // ---- table ----
        (
            "table add",
            Data::TableAdded {
                id: "table1".into(),
                rows: 3,
                cols: 4,
                style: "Table Grid".into(),
                message: "Table added".into(),
            },
        ),
        (
            "table list",
            Data::TableList {
                tables: vec![TableInfo {
                    index: 0,
                    id: Some("table1".into()),
                    rows: 3,
                    cols: 4,
                    style: Some("Table Grid".into()),
                }],
            },
        ),
        (
            "table get",
            Data::TableGot {
                id: Some("table1".into()),
                index: None,
                rows: 2,
                cols: 2,
                data: vec![
                    vec!["Region".into(), "Revenue".into()],
                    vec!["EMEA".into(), "1.2M".into()],
                ],
            },
        ),
        (
            "table set-cell",
            Data::CellSet {
                id: None,
                index: Some(0),
                row: 1,
                col: 1,
                value: "1.3M".into(),
                message: "Cell set".into(),
            },
        ),
        (
            "table set-range",
            Data::TableRangeSet {
                id: None,
                index: Some(0),
                rows_written: 2,
                header: true,
                message: "Range set".into(),
            },
        ),
        (
            "table add-row",
            Data::TableRowAdded {
                id: Some("table1".into()),
                index: None,
                message: "Row added".into(),
            },
        ),
        (
            "table add-column",
            Data::TableColumnAdded {
                id: Some("table1".into()),
                index: None,
                message: "Column added".into(),
            },
        ),
        (
            "table delete-row",
            Data::TableRowDeleted {
                id: None,
                index: Some(0),
                row: 2,
                message: "Row deleted".into(),
            },
        ),
        (
            "table delete-column",
            Data::TableColumnDeleted {
                id: None,
                index: Some(0),
                col: 3,
                message: "Column deleted".into(),
            },
        ),
        // ---- image ----
        (
            "image add",
            Data::ImageAdded {
                id: "img1".into(),
                path: "chart.png".into(),
                width: Some(4.0),
                height: None,
                message: "Image added".into(),
            },
        ),
        (
            "image list",
            Data::ImageList {
                images: vec![ImageInfo {
                    index: 0,
                    width: 3_840_000,
                    height: 2_160_000,
                    width_inches: Some(4.0),
                    height_inches: Some(2.25),
                }],
                count: 1,
            },
        ),
        (
            "image get",
            Data::ImageGot(ImageInfo {
                index: 0,
                width: 3_840_000,
                height: 2_160_000,
                width_inches: Some(4.0),
                height_inches: Some(2.25),
            }),
        ),
        (
            "image resize",
            Data::ImageResized {
                index: 0,
                width: Some(5.0),
                height: None,
                message: "Image resized".into(),
            },
        ),
        (
            "image delete",
            Data::ImageDeleted {
                index: 0,
                message: "Image deleted".into(),
            },
        ),
        // ---- toc ----
        (
            "toc add",
            Data::TocAdded {
                id: "toc1".into(),
                levels: "1-3".into(),
                message: "Table of contents added".into(),
            },
        ),
        (
            "toc update",
            Data::TocUpdateHint {
                message: "Open in Word and press F9 to update the TOC".into(),
            },
        ),
        // ---- section ----
        (
            "section list",
            Data::SectionList {
                sections: vec![SectionInfo {
                    index: 0,
                    orientation: "portrait".into(),
                    start_type: "next_page".into(),
                }],
                count: 1,
            },
        ),
        (
            "section info",
            Data::SectionDetail(SectionDetail {
                index: 0,
                orientation: "portrait".into(),
                page_width: Some(8.5),
                page_height: Some(11.0),
                top_margin: Some(1.0),
                bottom_margin: Some(1.0),
                left_margin: Some(1.0),
                right_margin: Some(1.0),
            }),
        ),
        (
            "section add",
            Data::SectionAdded {
                start_type: "next_page".into(),
                message: "Section added".into(),
            },
        ),
        (
            "section page-break",
            Data::PageBreakInserted {
                id: "para3".into(),
                message: "Page break inserted".into(),
            },
        ),
        // ---- page ----
        (
            "page margins",
            Data::MarginsSet {
                section: 0,
                top: Some(0.8),
                bottom: Some(0.8),
                left: None,
                right: None,
                unit: "inches".into(),
                message: "Margins set".into(),
            },
        ),
        (
            "page orientation",
            Data::OrientationSet {
                section: 0,
                orientation: "landscape".into(),
                message: "Orientation set".into(),
            },
        ),
        (
            "page size",
            Data::PageSizeSet {
                section: 0,
                width: Some(8.27),
                height: Some(11.69),
                unit: "inches".into(),
                message: "Page size set".into(),
            },
        ),
        (
            "page header",
            Data::HeaderSet {
                section: 0,
                header: "Confidential".into(),
                message: "Header set".into(),
            },
        ),
        (
            "page footer",
            Data::FooterSet {
                section: 0,
                footer: "Q3 2026".into(),
                message: "Footer set".into(),
            },
        ),
        (
            "page page-numbers",
            Data::PageNumbersAdded {
                section: 0,
                align: "center".into(),
                message: "Page numbers added".into(),
            },
        ),
        (
            "page columns",
            Data::ColumnsSet {
                section: 0,
                columns: 2,
                message: "Columns set".into(),
            },
        ),
        // ---- meta ----
        (
            "meta describe",
            Data::MetaDescribe(json!({
                "schema_version": 1,
                "document": {"title": "Quarterly Report"},
                "sections": {},
                "tables": {}
            })),
        ),
        (
            "meta get-document",
            Data::MetaDocumentGot {
                metadata: json!({"title": "Quarterly Report"}),
                message: "Document metadata".into(),
            },
        ),
        (
            "meta set-document",
            Data::MetaDocumentSet {
                metadata: json!({"title": "Quarterly Report", "status": "final"}),
                message: "Document metadata set".into(),
            },
        ),
        (
            "meta get-section",
            Data::MetaSectionGot {
                name: "summary".into(),
                metadata: json!({"owner": "finance"}),
            },
        ),
        (
            "meta set-section",
            Data::MetaSectionSet {
                name: "summary".into(),
                metadata: json!({"owner": "finance"}),
                message: "Section metadata set".into(),
            },
        ),
        (
            "meta get-table",
            Data::MetaTableGot {
                id: "table1".into(),
                schema: json!({"columns": [{"name": "Region", "type": "string"}]}),
            },
        ),
        (
            "meta set-table",
            Data::MetaTableSet {
                id: "table1".into(),
                schema: json!({"columns": [{"name": "Region", "type": "string"}]}),
                message: "Table schema set".into(),
            },
        ),
        (
            "meta history",
            Data::MetaHistory {
                history: vec![HistoryEntry {
                    timestamp: "2026-09-18T10:00:00".into(),
                    command: "paragraph add".into(),
                    target: "para1".into(),
                    summary: "Paragraph added".into(),
                    details: json!({}),
                }],
            },
        ),
        // ---- batch ----
        (
            "batch run",
            Data::BatchRun {
                script: "script.json".into(),
                commands_executed: 5,
                results: vec![json!({"status": "ok", "message": "", "data": {"count": 12}})],
                message: "Batch complete: 5/5 commands ok".into(),
            },
        ),
        (
            "batch template",
            Data::BatchTemplate {
                template: "report".into(),
                output: "script.json".into(),
                commands: 6,
                message: "Template written".into(),
            },
        ),
        // ---- calc ----
        (
            "calc read",
            Data::CalcRead {
                path: "report.docx".into(),
                table_id: Some("table1".into()),
                table_index: None,
                rows: 2,
                columns: vec!["Region".into(), "Revenue".into()],
                data: vec![json!({"Region": "EMEA", "Revenue": "1.2M"})],
                message: "Read 2 rows".into(),
            },
        ),
        (
            "calc stats",
            Data::CalcStats {
                path: "report.docx".into(),
                statistics: json!({"Revenue": {"mean": 20.0, "count": 3}}),
                message: "Statistics computed".into(),
            },
        ),
        (
            "calc aggregate",
            Data::CalcAggregate {
                path: "report.docx".into(),
                group_by: "Region".into(),
                agg_column: "Revenue".into(),
                agg_func: "sum".into(),
                result: vec![json!({"Region": "EMEA", "Revenue_sum": 3.4})],
                message: "Aggregated 1 group(s)".into(),
            },
        ),
        (
            "calc filter",
            Data::CalcFilter {
                path: "report.docx".into(),
                column: "Revenue".into(),
                operator: ">".into(),
                value: "1.0".into(),
                result: vec![json!({"Region": "EMEA", "Revenue": 1.2})],
                message: "1 row(s) matched".into(),
            },
        ),
        (
            "calc transform",
            Data::CalcTransform {
                path: "report.docx".into(),
                operations: json!([{"op": "add_column", "name": "VAT", "expr": "Revenue * 0.2"}]),
                result: vec![json!({"Region": "EMEA", "Revenue": 1.2, "VAT": 0.24})],
                message: "Transformed 1 row(s)".into(),
            },
        ),
    ];
    #[cfg(feature = "dev")]
    out.extend(dev_examples());
    out
}

/// Dev-only payloads (adr/0015) — same contract, same smoke test.
#[cfg(feature = "dev")]
fn dev_examples() -> Vec<(&'static str, Data)> {
    vec![
        (
            "dev setup",
            Data::DevSetup {
                path: ".sandbox".into(),
                home: ".sandbox/.poet".into(),
                created: true,
            },
        ),
        (
            "dev clean",
            Data::DevClean {
                removed: true,
                path: ".sandbox".into(),
            },
        ),
    ]
}

#[cfg(test)]
mod tests {
    use super::envelope_examples;
    use crate::core::error::PoetError;
    use crate::core::output::{ok, render, to_json};

    /// Every registered example renders a well-formed `ok` envelope whose
    /// schema is exact (three keys, no code/details) and whose `data`
    /// round-trips to the independently serialized example.
    #[test]
    fn envelope_smoke_round_trips_every_example() {
        for (cmd, data) in envelope_examples() {
            let expected = serde_json::to_value(&data).expect("example must serialize");
            let (json, is_error) = render(&Ok(data.clone()));
            assert!(!is_error, "{cmd}: envelope reported error");
            let env: serde_json::Value =
                serde_json::from_str(&json).unwrap_or_else(|e| panic!("{cmd}: invalid JSON: {e}"));
            let keys: Vec<&str> = env
                .as_object()
                .expect("{cmd}: envelope is an object")
                .keys()
                .map(String::as_str)
                .collect();
            assert_eq!(keys, ["status", "message", "data"], "{cmd}: key set");
            assert_eq!(env["status"], "ok", "{cmd}: status");
            assert_eq!(
                env["message"].as_str().unwrap_or("<absent>"),
                data.message(),
                "{cmd}: envelope message must mirror data.message()"
            );
            assert_eq!(&env["data"], &expected, "{cmd}: data round-trip mismatch");
            assert!(json.ends_with('\n'), "{cmd}: trailing newline");
        }
    }

    /// Words' message-placement quirk, pinned per example: lifecycle commands
    /// (plus the dev tooling) carry the envelope message; content commands
    /// keep it inside `data` only.
    #[test]
    fn message_placement_follows_the_words_quirk() {
        for (cmd, data) in envelope_examples() {
            let lifecycle = cmd.starts_with("document new")
                || cmd.starts_with("document open")
                || cmd.starts_with("document save")
                || cmd.starts_with("document close")
                || cmd.starts_with("dev ");
            if lifecycle {
                assert!(!data.message().is_empty(), "{cmd}: lifecycle message empty");
            } else {
                assert_eq!(data.message(), "", "{cmd}: content message must be empty");
            }
        }
    }

    /// The error envelope contract holds for every `PoetError` variant:
    /// exact key set, stable code, empty `details`.
    #[test]
    fn envelope_renders_every_error_variant() {
        let cases = vec![
            ("session_error", PoetError::Session("x".into())),
            ("validation_error", PoetError::Validation("x".into())),
            ("metadata_error", PoetError::Metadata("x".into())),
            ("calculation_error", PoetError::Calculation("x".into())),
            ("file_error", PoetError::File("x".into())),
            ("not_found", PoetError::NotFound("x".into())),
            ("conflict", PoetError::Conflict("x".into())),
            ("document_state", PoetError::DocumentState("x".into())),
            ("unsupported", PoetError::Unsupported("x".into())),
            ("not_implemented", PoetError::NotImplemented("x".into())),
            ("internal", PoetError::Internal("x".into())),
        ];
        for (code, err) in cases {
            assert_eq!(err.code(), code, "code drift for {code}");
            let (json, is_error) = render(&Err(err));
            assert!(is_error, "{code}: envelope reported ok");
            let env: serde_json::Value =
                serde_json::from_str(&json).unwrap_or_else(|e| panic!("{code}: invalid JSON: {e}"));
            let keys: Vec<&str> = env
                .as_object()
                .expect("envelope is an object")
                .keys()
                .map(String::as_str)
                .collect();
            assert_eq!(keys, ["status", "message", "code", "details"], "{code}");
            assert_eq!(env["status"], "error", "{code}");
            assert_eq!(env["code"], code, "{code}");
            assert_eq!(env["details"], serde_json::json!({}), "{code}");
        }
    }

    /// The registry keys are unique — a duplicated label would silently hide
    /// an example from per-command auditing.
    #[test]
    fn example_labels_are_unique() {
        let mut seen: Vec<&str> = envelope_examples().iter().map(|(cmd, _)| *cmd).collect();
        let total = seen.len();
        seen.sort_unstable();
        seen.dedup();
        assert_eq!(seen.len(), total, "duplicate example label");
    }

    /// `ok()` mirrors `render(Ok(..))` shape (used by callers that pre-shape).
    #[test]
    fn ok_direct_matches_render() {
        let data = crate::models::data::Data::ParagraphCount { count: 3 };
        assert_eq!(to_json(&ok(&data)), render(&Ok(data.clone())).0);
    }
}
